export { Header } from './Header/Header';
export { Footer } from './Footer/Footer';
export { TopRatedMoviesLayout } from './TopRated/Movie/Movie';
export { TopRatedShowsLayout } from './TopRated/TvShows/TvShow';
export { Pagination } from './Pagination/Pagination';
export { TvShowsPagination } from './Pagination/TvShowPagination'
export { MoviesLayout } from './Layouts/MovieLayout/MovieLayout';
export { TvShowsLayout } from './Layouts/TvShowLayout/TvShowsLayout';
export { MovieDetail } from './Details/MovieDetails';
export { TvShowDetail } from './Details/TvShowDetails';